### ISSUE TITLE
Handle horizontal rules like "* * *"

### ISSUE THREAD

**Issue by xrat** [bert-github/gf-markdown-awk#13]
Even with the fix for #12 I found that e.g. `* * *` was interpreted as list items rather than a horizontal rule. To reproduce:

``` bash
$ echo -e 'Test\n\n- - -\n' \
| awk '@include "markdown.awk"; { lines = lines $0 "\n" }
END { printf "%s", markdown::to_html(lines) }' | tr -d \\n ; echo
<p>Test</p><ul><li><ul><li><ul><li></li></ul></li></ul></li></ul>
```

A fix is to move the lines that i.a. match `* * *` in `type_of_line()`, i.e.

https://github.com/bert-github/gf-markdown-awk/blob/dfb2f6f58980e13130e4aaa9ba324bc85b66e998/markdown.awk#L487-L488

before the 1st line that matches lists

https://github.com/bert-github/gf-markdown-awk/blob/dfb2f6f58980e13130e4aaa9ba324bc85b66e998/markdown.awk#L471

**Comment by bert-github** [comment]
Thanks, @xrat!
